build:
  image: docker:1.10.3
  environment:
    - DOCKER_HUB_USERNAME=$$DOCKER_HUB_USERNAME
    - DOCKER_HUB_PASSWORD=$$DOCKER_HUB_PASSWORD
    - DOCKER_HUB_EMAIL=$$DOCKER_HUB_EMAIL
  commands:
    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD -e $DOCKER_HUB_EMAIL
    - docker build -t datagov/catalog:2.3.$$BUILD_NUMBER .
    - docker push datagov/catalog:2.3.$$BUILD_NUMBER
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

deploy:
  ssh:
    host: catalog.dev.datagov.us
    user: ubuntu
    port: 22
    commands:
      - git clone https://github.com/GSA/catalog-app.git
      - cd catalog-app
      - git checkout drone
      - docker-compose down
      - docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
      - cd ../
      - rm -rf catalog-app
