build:
  image: docker
  environment:
    - DOCKER_HUB_USERNAME=$$DOCKER_HUB_USERNAME
    - DOCKER_HUB_PASSWORD=$$DOCKER_HUB_PASSWORD
    - DOCKER_HUB_EMAIL=$$DOCKER_HUB_EMAIL
  commands:
    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD -e $DOCKER_HUB_EMAIL
    - docker build -t datagov/catalog-app:2.3.$$BUILD_NUMBER .
    - docker push datagov/catalog-app:2.3.$$BUILD_NUMBER
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
