catalog-web:
  build: .
  ports:
   - "80:80"
  links:
   - catalog-redis
   - catalog-db
   - catalog-solr
catalog-redis:
  image: redis
catalog-db:
  build: docker/db
catalog-solr:
  build: docker/solr
catalog-harvester:
  build: docker/harvester
  links:
   - catalog-redis
   - catalog-db
   - catalog-solr
