version: '3'
services:
  solr:
    # image: datagov/catalog-solr:latest
    build: ./docker/catalog-solr
  app:
    build:
      context: .
      dockerfile: "Dockerfile-report"
    environment:
      CKAN_SITE_URL: http://localhost:8080
    env_file:
      'variables.env'
    volumes:
      - .:/opt/catalog-app
      - ckan:/user/lib/ckan
      # - /tmp/ckan/csv:/tmp/ckan/csv
    # depends_on:
    #   - db
    #   - solr
    #   - redis
    # command: ["/wait-for-it.sh", "db:5432", "--", "/configure_app.sh", "/configure_report.sh"]
    ports:
      - "5000:5000"
      - "8080:80"
  # harvester-fetch-consumer:
  #   build: .
  #   command: fetch-consumer --wait-for-dependencies
  #   volumes:
  #     - ckan:/usr/lib/ckan
  # harvester-gather-consumer:
  #   build: .
  #   command: gather-consumer --wait-for-dependencies
  #   volumes:
  #     - ckan:/usr/lib/ckan
  redis:
    build: ./docker/redis
  db:
    image: datagov/catalog-db:latest
    env_file:
      'variables.env'

  # fgdc2iso:
  #   image: datagov/catalog-fgdc2iso:latest
  #   environment:
  #     SIGNATURE:
  # pycsw:
  #   image: datagov/catalog-pycsw:latest
  #   links:
  #     - app
  #     - db
  #   command: start-pycsw --wait-for-dependencies
  # nginx:
  #   image: datagov/catalog-nginx:latest
  #   ports:
  #     - "80:80"
  #   links:
  #     - app
  #     - pycsw
  #   command: /entrypoint.sh --wait-for-dependencies
  # scheduler:
  #   image: datagov/catalog-scheduler:latest
  #   links:
  #     - app
  #     - redis
  #     - db
  #     - solr
  #     - fgdc2iso
  #   volumes:
  #   - /var/run/docker.sock:/var/run/docker.sock
  #   - ./docker-compose.yml:/docker-compose.yml
volumes:
  .:
    driver: local
  ckan:
    driver: local
  # /tmp/ckan/csv:
  #   driver: local
