version: '3'
services:
  app:
    build: .
    env_file:
      .env.catalog
    depends_on:
      - redis
      - db
      - solr
    volumes:
      - .:/opt/catalog-app
      - ckan:/usr/lib/ckan
      - /tmp/ckan
      - ckan_storage:/var/lib/ckan
    ports:
      - "5000:5000"
      - "8080:80"

  db:
    image: datagov/catalog-db:latest
    environment:
      POSTGRES_USER: postgres
      DB_CKAN_USER: ckan
      DB_CKAN_PASSWORD: pass
      DB_CKAN_DB: ckan
      DB_PYCSW_DB: pycsw

  fgdc2iso:
    image: datagov/catalog-fgdc2iso:latest
    environment:
      SIGNATURE:

  redis:
    build: ./docker/redis

  solr:
    image: datagov/catalog-solr:latest


volumes:
  ckan:
  ckan_storage:
