version: '3'
services:
  ckan:
    build: .
    env_file:
      .env.catalog
    depends_on:
      - redis
      - db
      - solr
    volumes:
      - .:/opt/catalog-app
      - ckan:/usr/lib/ckan
      - /tmp/ckan
      - ckan_storage:/var/lib/ckan
    ports:
      - "5000:5000"
      - "8080:80"

  db:
    image: datagov/catalog-db:ckan_2.8
    environment:
      POSTGRES_USER: postgres
      DB_CKAN_USER: ckan
      DB_CKAN_PASSWORD: ckan
      DB_CKAN_DB: ckan
      DB_DATASTORE: datastore
      DB_DATASTORE_RO_USER: datastore_ro
      DB_DATASTORE_RO_PASS: datastore

  fgdc2iso:
    image: datagov/catalog-fgdc2iso:latest
    environment:
      SIGNATURE:

  redis:
    build: ./docker/redis

  solr:
    image:  datagov/catalog-solr:ckan_2.8


volumes:
  ckan:
  ckan_storage:
  solr_data:
