version: '3'
services:
  app:
    build:
      context: .
      dockerfile: "Dockerfile-harvest"
      args:
        - POSTGRES_USER=${POSTGRES_USER}
        - DB_CKAN_USER=${DB_CKAN_USER}
        - DB_CKAN_PASSWORD=${DB_CKAN_PASSWORD}
        - DB_CKAN_DB=${DB_CKAN_DB}
        - DB_PYCSW_DB=${DB_PYCSW_DB}
        - CKAN_SITE_URL=${CKAN_SITE_URL}
    volumes:
      - .:/opt/catalog-app
      - ckan:/usr/lib/ckan
    ports:
      - "5000:5000"
      - "8080:80"
  # fgdc2iso:
  #   image: datagov/catalog-fgdc2iso:latest
  #   environment:
  #     SIGNATURE:
  # pycsw:
  #   image: datagov/catalog-pycsw:latest
  #   links:
  #     - app
  #     - db
  #   command: start-pycsw --wait-for-dependencies
  # nginx:
  #   image: datagov/catalog-nginx:latest
  #   ports:
  #     - "80:80"
  #   links:
  #     - app
  #     - pycsw
  #   command: /entrypoint.sh --wait-for-dependencies
  scheduler:
    # build: ./docker/catalog-scheduler
    image: datagov/catalog-scheduler:latest
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "./docker-compose.yml:/docker-compose.yml"
volumes:
  .:
    driver: local
  ckan:
    driver: local
