app:
  build: .
  ports:
   - "80:80"
  environment:
    CKAN_SITE_URL: http://catalog.dev
#  volumes:
#   - ./src:/usr/lib/ckan/src
  links:
   - redis
   - db
   - solr
   - fgdc2iso
  command: app --wait-for-dependencies
harvester-fetch-consumer:
  build: .
  links:
   - app
   - redis
   - db
   - solr
   - fgdc2iso
  command: fetch-consumer --wait-for-dependencies
harvester-gather-consumer:
  build: .
  links:
   - app
   - redis
   - db
   - solr
   - fgdc2iso
  command: gather-consumer --wait-for-dependencies
redis:
  image: redis
db:
  build: docker/db
  environment:
    POSTGRES_USER: postgres
    DB_CKAN_USER: ckan
    DB_CKAN_PASSWORD: pass
    DB_CKAN_DB: ckan
    DB_PYCSW_DB: pycsw
solr:
  build: docker/solr
fgdc2iso:
  build: docker/fgdc2iso
pycsw:
  build: docker/pycsw
datavolume:
  build: docker/datavolume
