app:
  image: datagov/catalog
  ports:
   - "80:80"
  environment:
    CKAN_SITE_URL: 52.207.218.22
  links:
   - redis
   - db
   - solr
   - fgdc2iso
  command: app --wait-for-dependencies
harvester-fetch-consumer:
  image: datagov/catalog
  links:
   - app
   - redis
   - db
   - solr
   - fgdc2iso
  command: fetch-consumer --wait-for-dependencies
harvester-gather-consumer:
  image: datagov/catalog
  links:
   - app
   - redis
   - db
   - solr
   - fgdc2iso
  command: gather-consumer --wait-for-dependencies
redis:
  image: redis
db:
  image: datagov/catalog-db
  environment:
    POSTGRES_USER: postgres
    DB_CKAN_USER: ckan
    DB_CKAN_PASSWORD: pass
    DB_CKAN_DB: ckan
    DB_PYCSW_DB: pycsw
solr:
  image: datagov/catalog-solr
fgdc2iso:
  image: datagov/catalog-fgdc2iso
